### ISSUE TITLE
Import/Export feature

### ISSUE THREAD

**Issue by AliHichem** [michelsalib/BCCCronManagerBundle#42]
Thank you for this bundle, it's nice to have and would be nicer if we can get a feature like import / export because think about it : if I'm using this bundle than I'm probably dealing with big number of cron jobs and if it is the case then what to do with creating the crons on a production server ? should I create them one by one again ?

I'm thinking about a way to store the cron config in a non-accessible by users config file that will be part of the code and at the same time a way to warmup the cron on install or update. what do you think ?

**Comment by NicolasBadey** [comment]
Yes it's interesting, a basic XML import export, and import create cron in crontab.
