### ISSUE TITLE
Missing information regarding bootstrap_less filter

### ISSUE THREAD

**Issue by insaneDev** [michelsalib/BCCCronManagerBundle#56]
After a clean install got this error whenever trying to access cron-manage route.

An exception has been thrown during the compilation of a template ("There is no "bootstrap_less" asset.") in "BCCCronManagerBundle::layout.html.twig".

**Comment by NicolasBadey** [comment]
Use tag v2.6, if you using 2.4 tag be carreful about documentation, it's not the same

**Comment by insaneDev** [comment]
I use symfony2.3, is´t compatible?

**Comment by NicolasBadey** [comment]
yes but with this tag :
"bcc/cron-manager-bundle": "v2.3.0"

**Comment by insaneDev** [comment]
I use that flag on my composer.json

**Comment by NicolasBadey** [comment]
Sorry for delay, you have to follow the documentation of the Tag, you miss :

imports:
    - { resource: @BCCCronManagerBundle/Resources/config/assetic.yml }

here at the end :
https://github.com/michelsalib/BCCCronManagerBundle/blob/v2.3.0/README.markdown
