### ISSUE TITLE
Multiple translation entries

### ISSUE THREAD

**Issue by nbk195** [michelsalib/BCCCronManagerBundle#58]
Hi, 
Thank you fro your amazing work, it's great. 
I'm using Symfony 2.6 and handle my translations via LexikTranslations Bundle. 
When I import your translations files into Lexik table, i encounter issue with duplicate keys. 

In facts the following entries are duplicate in your xliff files : 
- error
- success
- unknown

It is possible to remove it from source ?
Thanks and see you

**Comment by NicolasBadey** [comment]
could you do a pull request ? 
Thanks

**Comment by nbk195** [comment]
Sorry forgot to mention,
Mac OS X yosemite

**Comment by nbk195** [comment]
Hi, 

after further tests, twig trans handle very well unique catalogue entry and capitalize call. 
With an unique 'unknown' entry in my catalogue, i may call 'unknown' and get 'unknown' in my template, and if i call 'Unknown' i get 'Unknown'. 

The only point very a little improvement can be done, is in index.html.twig, by adding a | Capitalize in  cron.status translation. 
I'll make pull request and let you choose to commit it or not. 

And thanks again for your bundle it's really geat.
