### ISSUE TITLE
Fatal Error on Clean Symfony 2.3 Installation

### ISSUE THREAD

**Issue by mandre00** [michelsalib/BCCCronManagerBundle#60]
FatalError discovered: Notice: Undefined offset: 1 in /var/www/host/deploy/releases/20150301225636/vendor/bcc/cron-manager-bundle/BCC/CronManagerBundle/Manager/Cron.php line 161 [] []

request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\DummyException: "" at /var/www/host/deploy/releases/20150301225636/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php line 162 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\DummyException(code: 0):  at /var/www/host/deploy/releases/20150301225636/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php:162)"} []

Ok i found the problem in der user crontab, here was a entry which disables sending of Mails:

MAILTO=""

It seems like the code needs a check if the parsed line is an array of 5 elements.

**Comment by NicolasBadey** [comment]
Ok, I close issu

**Comment by mandre00** [comment]
i don't think that a close is okay, because it is valid that you can use MAILTO="" in the first line of a crontab to subpress sending of mails. so it would be nice if you add a check if the array of each line has the expected length.

**Comment by NicolasBadey** [comment]
use "bcc/cron-manager-bundle": "v2.6.*" and it will be good :)
