### ISSUE TITLE
Impossible to add a cron task

### ISSUE THREAD

**Issue by BHKDev** [michelsalib/BCCCronManagerBundle#61]
Hi, 
This is my config : Symfony 2.6 , BCCCronManagerBundle v.2.6.
I cannot creat a new cron task within the bundle.
On top of my page , an error message is writen : 
' crontab ' is not recognized as an internal or external command, executable program or batch file.
Maybe i did something wrong.

Thank you in advance !
Bob

**Comment by NicolasBadey** [comment]
What is your OS ? You just don't have crontab command (linux)

**Comment by BHKDev** [comment]
I'm on Windows Seven, and XAMPP architecture.

**Comment by NicolasBadey** [comment]
crontab exists on Linux or Unix, you should not use this bundle in Windows env

**Comment by BHKDev** [comment]
Oh Ok, thanks. i'll try it on my web hosting, it could work then. I'll keep you posted. thanks
