### ISSUE TITLE
Symfony 3.0 

### ISSUE THREAD

**Issue by mogilvie** [michelsalib/BCCCronManagerBundle#68]
Hi,
Please update composer to permit the use of symfony2 v 3+
"symfony/symfony": "~2"
to 
"symfony/symfony": "~3"

Thanks

**Comment by NicolasBadey** [comment]
I have created a 3.0 branch, could you do a PR ?

Thanks

**Comment by xabbuh** [comment]
@NicolasBadey Do you really want to maintain different versions of the bundle to support different Symfony versions?

**Comment by skonsoft** [comment]
Hello,
Thank you for your work. I think that it's a very good idea to keep a branch for Symfony 2.X. At least for one year, There are thousands of projects that are developped with SF2 and they will not be upgraded soonly to v3.

**Comment by mogilvie** [comment]
I would expect the intention is to maintain backward compatibility with 2.X. The current version may even require very little modification.

However when trying to upgrade to Symfony2 3.0 I ran into the issue of the CronManager bundle requiring "symfony/symfony": "~2" which only permits versions greater than 2.0.0 and less than 3.0.0. Resulting in failed composer updates.

I suggest just changing and testing the composer requirements to a minimum version of  >=2

**Comment by NicolasBadey** [comment]
@xabbuh you are right, I will merge PR in MAster and just create a Tag.

PR is fealing for now, I'm not using the bundle in my new company and we are not on 3.0 so I cannot test it for now

**Comment by NicolasBadey** [comment]
done with last PR 
https://github.com/michelsalib/BCCCronManagerBundle/commit/c611997ccfc484e45425a84b181437c9ba775174
