### ISSUE TITLE
Doctrine 2.5.5 Support ?

### ISSUE THREAD

**Issue by mlelong** [michelsalib/BCCCronManagerBundle#78]
I can see that cronmanager-bundle need doctrine v2.4.8 to run. Will it support the last doctrine release (aka 2.5.5) in the future ?  

 - dspsofts/cronmanager-bundle v1.2.2 requires doctrine/orm ~2.2,>=2.2.3,<2.5 -> satisfiable by doctrine/orm[2.2.3, 2.2.x-dev, 2.3.0, 2.3.0-BETA1, 2.3.0-RC1, 2.3.0-RC2, 2.3.0-RC3, 2.3.0-RC4, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.x-dev, 2.4.0-BETA1, 2.4.0-BETA2, 2.4.0-RC1, 2.4.0-RC2, 2.4.x-dev, v2.3.6, v2.4.0, v2.4.1, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8] but these conflict with your requirements or minimum-stability.

**Comment by xabbuh** [comment]
@mlelong Your issue doesn't seem to be related to this bundle (note the package name `dspsofts/cronmanager-bundle` in the error message while the package name of this bundle is `bcc/cron-manager-bundle`).

**Comment by mlelong** [comment]
Clearly my bad, sorry for trouble.
