### ISSUE TITLE
Security is somehow missing

### ISSUE THREAD

**Issue by leotiger** [michelsalib/BCCCronManagerBundle#81]
Thx, nice bundle. You should thing about a security parameter setting to protect the interface. Exposing cron without obliging to set allowed roles is a security problem.

u

**Comment by CoalaJoe** [comment]
You can do that in your security.yml

**Comment by leotiger** [comment]
@CoalaJoe 

True, but at least you should indicate this in the documentation and it does not work with 

```
security:
    access_control:
        # this is a catch-all for the admin area
        # additional security lives in the controllers
        - { path: '^/cron/manager', roles: [ROLE_ADMIN] }
```

I've implemented security inside of the bundle (in a private fork) using a configuration parameter for this reason.

**Comment by CoalaJoe** [comment]
Good to see. I may also need to do a fork, there are a few typos in the translation keys and the bundle is not ready for Symfony 3.... bummer the developer doesn't care for his projects.

**Comment by NicolasBadey** [comment]
AsseticBundle is droped, Bundle works on Sf3.3 with tag v3.1

**Comment by NicolasBadey** [comment]
Doc added, fell free to do Pull Request from you fork for help the community to maintain the bundle

**Comment by CoalaJoe** [comment]
There are some translations that i fixed, and some small stuff. I'll look into it later.
