### ISSUE TITLE
addFlash fails when calling DefaultController Actions

### ISSUE THREAD

**Issue by chess-server** [michelsalib/BCCCronManagerBundle#86]
Under Symfony 4 and php 7.1, I do get errors when calling any action in the DefaultController. It seems that  the CronManager gives back a NULL as Process Output, when everything is ok. ($cm->getOutput() in the code). The method addFlash() expects a string in the second position. Null is not accepted.

Issue is resolved if in its declaration in CronManager $output is set to an empty string.

**Comment by NicolasBadey** [comment]
fix with #87 commit
