### ISSUE TITLE
Override template layout.html.twig BCCCronManagerBundle

### ISSUE THREAD

**Issue by gicuturetchi** [michelsalib/BCCCronManagerBundle#89]
Hello,
I tried to override template layout.html.twig, I use symfony 3.4.
1. I created a folder inside /templates called /BCCCronManagerBundle
2. Inside /templates/BCCCronManagerBundle I created file : layout.html.twig.
3. I clear the cache but seems the override not working.

Could you help me please ?

**Comment by NicolasBadey** [comment]
Use the last tag for sf3.4, that will works now
