### ISSUE TITLE
Symfony4 supported?

### ISSUE THREAD

**Issue by jllaurado** [michelsalib/BCCCronManagerBundle#90]
Good morning,

I'm installing cronmanager 4.0 into a Symfony4.2 installation and I've got the following error:

Argument 2 passed to Symfony\Bundle\FrameworkBundle\Controller\Controller::addFlash() must be of the type string, null given, called in /home/j.llaurado/public_html/sapiface/vendor/bcc/cron-manager-bundle/BCC/CronManagerBundle/Controller/DefaultController.php on line 25

Before adding a control on that line, do you have this reported?

php 7.1.27
symfony 4.2.4
Using version ^4.0 for bcc/cron-manager-bundle

thanx!

**Comment by NicolasBadey** [comment]
I created a 4.2 tag for Sf4.2, works for me, tell me if it's good for you.
Thanks

**Comment by jllaurado** [comment]
It works flawless! Thanks for the quick solution! 

Great plugin BTW, a must in any Symfony project for us...

**Comment by NicolasBadey** [comment]
Thanks !
