### ISSUE TITLE
template error

### ISSUE THREAD

**Issue by benpic87** [michelsalib/BCCCronManagerBundle#98]
With Symfony 4.4
Uncaught PHP Exception InvalidArgumentException: "Malformed namespaced template name "@BCCCronManager:Default:edit.html.twig" (expecting "@namespace/template_name")." at /var/www/html/vendor/symfony/symfony/src/Symfony/Bridge/Twig/TwigEngine.php line 137

**Comment by NicolasBadey** [comment]
Hi, that have been fix with last PR on master
